
const LOCAL_BROKER_URL = 'mqtt://127.0.0.1';
const BOBO1_DOMAIN_NAME = 'bobo';
const HEARTBEAT_TOPIC = 'internal-general-heartbeat';
const RED_ALERT_NOTIFY_TOPIC = 'red-alert-notify';
const OPEN_SAFEHOUSE_TOPIC = 'lock-open';
const GENERAL_LOCK_ACKNOWLEDGE_TOPIC = 'internal-lock-acknowledge';

const LOCAL_SUBSCRIPTION_TOPICS = [
    HEARTBEAT_TOPIC,
    RED_ALERT_NOTIFY_TOPIC,
    OPEN_SAFEHOUSE_TOPIC,
    GENERAL_LOCK_ACKNOWLEDGE_TOPIC,
];

const MONGO_DB_URL = 'mongodb://localhost:27017';
const MONGO_DB_DATABASE = 'unit_management';
const MONGO_DB_TELEGRAM_USERS_DATABASE= "telegram_users";
const MONGO_DB_TELEGRAM_USERS_COLLECTION_NAME = 'chat_ids';
const MONGO_UNIT_COLLECTION_NAME = 'units';

module.exports = {
    HEARTBEAT_TOPIC,
    MONGO_DB_URL,
    MONGO_DB_DATABASE,
    MONGO_UNIT_COLLECTION_NAME,  
    RED_ALERT_NOTIFY_TOPIC,
    OPEN_SAFEHOUSE_TOPIC,
    GENERAL_LOCK_ACKNOWLEDGE_TOPIC,
    LOCAL_BROKER_URL,
    LOCAL_SUBSCRIPTION_TOPICS,
    MONGO_DB_TELEGRAM_USERS_DATABASE,
    MONGO_DB_TELEGRAM_USERS_COLLECTION_NAME,
    BOBO1_DOMAIN_NAME
};
